### ISSUE TITLE
UI feature requests

### ISSUE THREAD

**Issue by glasgowm148** [capt-nemo429/nautilus-wallet#4]
1. 'View' password button
2. Using the tab key works as enter/next when entering mnemonic 
3. `Send All` option to consolidate UTXOs
4. Making pending transactions more obvious / locking wallets until the transaction is confirmed.

**Comment by cafebedouin** [comment]
I'll add on:
5. Ability to delete a wallet
6. Ability to change wallet name

**Comment by capt-nemo429** [comment]
Thank you for you feedback all these requests will be added to our dev pipeline.

**Comment by Athanaze** [comment]
For the nfts, I would like a preview of each nft instead of the gray octogone.

I think using the Register 9 "Optional - link to the artwork (UTF-8 representation)" would work.

Thanks a lot for your work, using this wallet has been a great experience for me so far :)

**Comment by ilyaLibin** [comment]
version appear somewhere here in small.
![telegram-cloud-photo-size-4-5787428475735488424-y](https://user-images.githubusercontent.com/12880486/153838374-8a60fb3e-bf28-44ef-b24b-2dd05c255381.jpg)

**Comment by capt-nemo429** [comment]
I'm organizing the questions to help me keep track of what I have to do. So I have spliced this issue into small ones.

You can track UI issues [here](https://github.com/capt-nemo429/nautilus-wallet/issues?q=is%3Aopen+label%3Aenhancement+label%3Aui).
