### ISSUE TITLE
Add 'Send All' option on 'Send' tab

### ISSUE THREAD

**Issue by capt-nemo429** [capt-nemo429/nautilus-wallet#43]
Useful to consolidate UTxOs.

**Comment by cafebedouin** [comment]
Possibly either have send all to main, active or next address so consolidating is default behavior. It seems the more likely use case than sending all to some other address.

**Comment by capt-nemo429** [comment]
Makes sense, I need to design a good UX for that to avoid mistakes, some time ago, we had issues with users accidentally sending tokens to CoinEx with Yoroi.
