### ISSUE TITLE
Spending password? 

### ISSUE THREAD

**Issue by Axze-rgb** [capt-nemo429/nautilus-wallet#8]
Hello, 

I have a new wallet setup but I realize I did not setup a sending password. Is it possible to add or do I need to setup a new wallet account? Thanks

**Comment by CheddarMiner** [comment]
Hello, I have a similar issue.  I keep getting an error code telling me my password is wrong, and I am 99% sure it is right (there is always a chance I am wrong).  Is there a place we can change our spending password by entering our seed phrase?  If not, can we please create one?

**Comment by CheddarMiner** [comment]
> Hello, I have a similar issue. I keep getting an error code telling me my password is wrong, and I am 99% sure it is right (there is always a chance I am wrong). Is there a place we can change our spending password by entering our seed phrase? If not, can we please create one?

Figured it out from Reddit help.  
![IMG_1403](https://user-images.githubusercontent.com/101522745/158075066-c6e7c123-aeda-4633-a2ec-cb76c598feb1.jpg)

**Comment by capt-nemo429** [comment]
Just restore your wallet from mnemonic again, Nautilus will replace old password
