### ISSUE TITLE
Question: Will Nautilus Wallet support Trezor?

### ISSUE THREAD

**Issue by abartolo** [capt-nemo429/nautilus-wallet#9]
Congratulation on 3rd place! https://ergoplatform.org/en/blog/2022-03-01-ergohack-iii-results/

Not sure where else to ask the questions above.

Thanks!

**Comment by Yuxanju** [comment]
Yes it will but You will have to synchronize your wallet and then you debug it

**Comment by abartolo** [comment]
@Yuxanju Great to hear! Thanks and looking forward to using it then.
